apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-pv-volume
  labels:
      type: local
spec:
  storageClassName: auto
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mediawiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pv-claim
  namespace: thoughtworks
spec:
  storageClassName: auto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
