apiVersion: v1
kind: Service
metadata:
  namespace: thoughtworks 
  name: mediawiki-service
  labels:
    name: mediawiki-service
    app: mediawiki
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mediawiki
    tire: frontend
